# Catalog unit: valid only when generated by a stack (include pointed at the
# stack runtime location). In the plain library-parse context this file fails
# to evaluate — and must not sink the whole generation.
include "cloud" {
  path = find_in_parent_folders("terragrunt-cloud.hcl")
}
