name: Build and test code
on: [push, pull_request]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        golang-version: ["1.25.4"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: "^${{ matrix.golang-version }}"
      - name: Clear Go module cache
        run: go clean -modcache || true
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ matrix.os }}-${{ matrix.golang-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.golang-version }}-go-
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: go test -v -cover ./...
